import type { NextPage } from 'next'
// import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'



import { Head } from '@/components/Head'
import { Header } from '@/components/Header'
import { wonders, WonderBlock } from '@/components/WonderBlock';
import { FaqBlock } from '@/components/Faq'
import { Footer } from '@/components/Footer'

const HomePage = () => {

  return (

    <div className='text-3xl text-green-600 p-2'>

      Hello Geeks!

    </div>

  )

}


const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

      <Head />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

const TrueHome: NextPage = () => {


  return (
    <div className='h-full bg-black'>
      <Head />
      <div className="bg-zkforest">
        <div className="hero-img">
          <Header hidden={false} links={[]} />

          <div className='h-200'>

            <br />  <br />  <br /> <br />  <br />  <br />
            <div className="container flex mx-auto flex-wrap ">
              <div className="w-full sm:w-2/5 p-8 sm:py-20 ml-32">
                <h4>Dark Forest Players DAO</h4>
                <h1>ZK Forest </h1>
                <p className="font-display sm:text-2xl mt-8">
                  We need stable dark forest community round. <br />
                  More players, More developers, More fun.
                </p>
              </div>
              {/* <div className="w-full  sm:w-2/5 text-center p-10 bg-zkforest bg-gray-800/10 rounded self-center ">
                <h2>
                  1 round/1 month<br /> & earn $ZKF <br /> & Combinable NFTs
                </h2>
              </div> */}
              <div className="w-full  sm:w-2/5 text-center text-indigo-900 p-10 bg-green-200 rounded self-center ">
                <h2>
                  come to a new game <br/>
                  just like a new dream <br/>
                </h2>
              </div>


            </div>
          </div>
        </div>
      </div>



      <div className="w-full h-auto bg-off-200 py-8 flex shadow-inner px-20 bg-zkforest">
        <h4 className="mx-auto uppercase font-semibold">
          dark forest Plugin
        </h4>
      </div>



      <div id="wonders" className="flex justify-center">
        <div className="w-1/2 py-8 text-center mt-20">
          <h1 className="mb-4"> Dark Forest</h1>
          <p className="sm:text-2xl">
            Dark Forest is an MMO strategy game built with zkSNARKs on Gnosis Chain (formerly xDai). Players explore an infinite, procedurally-generated universe, conquering planets and growing a space empire.


            {' '}
          </p>
        </div>
      </div>

      <div className="grid gap-2 grid-cols-2 sm:grid-cols-4 px-2">
        {wonders.map((a, index) => {
          return (
            <WonderBlock key={index} name={a.name} id={a.id} order={a.order} url={a.url} />
          );
        })}
      </div>





      <FaqBlock />



      <Footer />
    </div>
  )



}

// export default Home
// export default HomePage
export default TrueHome